import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: ['400','600'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Portfolio software enginneer',
  description: 'Generated by create next app',
  keywords: ['software engineer', 'portfolio', 'development']
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
